//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FamilyMatters.Module.BusinessObjects
{

    public partial class Category : FamilyOwnedBase
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Category fParent;
        public Category Parent
        {
            get { return fParent; }
            set { SetPropertyValue<Category>(nameof(Parent), ref fParent, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        bool fIsExpense;
        public bool IsExpense
        {
            get { return fIsExpense; }
            set { SetPropertyValue<bool>(nameof(IsExpense), ref fIsExpense, value); }
        }
        [PersistentAlias("IIif([Parent] <> null, Concat([Parent.Name], ' : ', [Name], [Name]))")]
        public string Title
        {
            get { return (string)(EvaluateAlias(nameof(Title))); }
        }
    }

}
