//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FamilyMatters.Module.BusinessObjects
{

    public partial class Family : XPObject
    {
        string fFamilyName;
        public string FamilyName
        {
            get { return fFamilyName; }
            set { SetPropertyValue<string>(nameof(FamilyName), ref fFamilyName, value); }
        }
        User fCreatedBy;
        public User CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<User>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        string fMainPhone;
        public string MainPhone
        {
            get { return fMainPhone; }
            set { SetPropertyValue<string>(nameof(MainPhone), ref fMainPhone, value); }
        }
        [Association(@"UserFamilyReferencesFamily")]
        public XPCollection<UserFamily> UserFamilies { get { return GetCollection<UserFamily>(nameof(UserFamilies)); } }
    }

}
