//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FamilyMatters.Module.BusinessObjects
{

    public partial class UserFamily : XPObject
    {
        Family fFamily;
        [Association(@"UserFamilyReferencesFamily")]
        public Family Family
        {
            get { return fFamily; }
            set { SetPropertyValue<Family>(nameof(Family), ref fFamily, value); }
        }
        User fUser;
        [Association(@"UserFamilyReferencesUser")]
        public User User
        {
            get { return fUser; }
            set { SetPropertyValue<User>(nameof(User), ref fUser, value); }
        }
        Role fRole;
        public Role Role
        {
            get { return fRole; }
            set { SetPropertyValue<Role>(nameof(Role), ref fRole, value); }
        }
    }

}
